[program:yourcast]
directory=/home/yourcast/yourcast
command=/home/yourcast/yourcast/venv/bin/python main.py
stdout_logfile=/home/yourcast/out.log
stderr_logfile=/home/yourcast/err.log
autostart=true
autorestart=true
numprocs=1
stopasgroup=true
killasgroup=true
stopwaitsecs=30
