# This is a basic workflow to help you get started with Actions

name: Continous deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  deploy-build-restart:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      

      # Runs a set of commands using the runners shell
      - name: Push to production server and restart
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            # Pulling
            cd ${{ secrets.PROJECT_PATH }}
            git pull

            # Building
            python -V
            source venv/bin/activate
            python -m pip install -r requirements.txt

            # Configuring
            cat supervisor.conf > /etc/supervisor/conf.d/yourcast.conf
            supervisorctl reread
            supervisorctl update

            # Restarting
            cd ../
            supervisorctl restart yourcast

            echo "" > err.log
            echo "" > out.log
